version: '3.8'

services:
  backend:
    build: ./stock-backend
    ports:
      - "8000:8000"
    volumes:
      - ./stock-backend:/app
    environment:
      - DATABASE_URL=sqlite:///./stocks.db
    depends_on:
      - db

  frontend:
    build: ./stock-dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./stock-dashboard:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

